config/routes.rb
NoMercyChess::Application.routes.draw do
  resources :completions

  resources :lessons do 
    collection do
      #used for lesson building
      get 'builder'
      get :csv
      post :import
    end
    member do
      #used for a "test" at the end of a lesson
      get 'quizzes'
      get 'clone'
      get 'csv_lesson'
      get 'csv_lesson_moves'
      get 'csv_lesson_exercises'
    end
  end

  resources :exercises do
    collection do
      get :csv
      post :import
    end
    member do
      get 'practice'
      get 'clone'
      get 'quiz'
      get 'csv'
      # get 'builder'
    end
  end
  resources :moves do
    collection do
      get :csv
      post :import
    end
  end

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users

  get "home/pricing" 
  get "home/usedids"
  get "home/philosophy" 

end

app/models/move.rb
class Move < ActiveRecord::Base
  	attr_accessible :computer, :exercise_id, :explanation, :move_number, :piece_white, :starting_coordinate_white, :ending_coordinate_white, :piece_black, :starting_coordinate_black, :ending_coordinate_black

  	belongs_to :exercise

	def self.to_csv(all_items)
		CSV.generate do |csv|
		  csv << column_names
		  all_items.each do |item|
		    csv << item.attributes.values_at(*column_names)
		  end
		end
	end
	

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # Move.create! row.to_hash
      if find_by_id(row["id"])
        item = find_by_id(row["id"])
        item.attributes = row.to_hash.slice(*accessible_attributes)
        item.save!
      else
        item = Move.new
        item.attributes = row.to_hash.slice(*accessible_attributes)
        #this is code where I am going to try something)
        item.id = row.to_hash.slice("id")["id"].to_i
      
        item.save!
      end
    end
  end


end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all
    @move = Move.new
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @moves }
      # format.csv { render text: Move.to_csv(@moves), filename: "test.csv" }
      format.csv { 
        send_data(
          Move.to_csv(@moves),
          :type => 'application/excel',
          :filename => 'moves.csv',
          :disposition => 'attachment'
        ) 
      }

    end
  end

  # def csv
  #   @moves = Move.where(:move_number => "1")
  #   send_data(
  #     Move.to_csv(@moves),
  #     :type => 'text/csv',
  #     :filename => 'export.csv',
  #     :disposition => 'attachment'
  #   )
  # end


  # GET /moves/1
  # GET /moves/1.json
  def show
    @move = Move.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @move }
    end
  end

  # GET /moves/new
  # GET /moves/new.json
  def new
    @move = Move.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @move }
    end
  end

  # GET /moves/1/edit
  def edit
    @move = Move.find(params[:id])

    respond_to do |format|
      format.js
      format.html
    end
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(params[:move])

    respond_to do |format|
      if @move.save
        format.js
        format.html { redirect_to @move, notice: 'Move was successfully created.' }
        format.json { render json: @move, status: :created, location: @move }
      else
        format.html { render action: "new" }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /moves/1
  # PUT /moves/1.json
  def update
    @move = Move.find(params[:id])

    respond_to do |format|
      if @move.update_attributes(params[:move])
        format.js
        format.html { redirect_to @move, notice: 'Move was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move = Move.find(params[:id])
    @move.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to moves_url }
      format.json { head :no_content }
    end
  end

  def import
    Move.import(params[:file])
    redirect_to builder_lessons_path, notice: "Moves imported."
  end
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/_form.html.erb
<%= simple_form_for @move, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>

  <div class="control-group">
    <%= f.label :exercise_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :exercise_id, Exercise.all, :id, :title %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :move_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :move_number %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :computer, :class => 'control-label' %>
    <div class="controls">
      <%= f.radio_button :computer, true %> White
      <%= f.radio_button :computer, false %> Black
    </div>
  </div>    
  <div class="control-group">
    <%= f.label :piece_white, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :piece_white, [['...','...'],['♟','♟'],['♞','♞'],['♝','♝'],['♜','♜'],['♛','♛'],['♚','♚']]%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :starting_coordinate_white, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :starting_coordinate_white, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ending_coordinate_white, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ending_coordinate_white, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :piece_black, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :piece_black, [['...','...'],['♟','♟'],['♞','♞'],['♝','♝'],['♜','♜'],['♛','♛'],['♚','♚']]%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :starting_coordinate_black, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :starting_coordinate_black, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ending_coordinate_black, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ending_coordinate_black, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :explanation, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :explanation, :class => 'text_area' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                moves_path, :class => 'btn' %>
  </div>
<% end %>

app/views/moves/_formjs.html.erb
<%= simple_form_for(@move, :remote => true) do |f| %>
  <%= f.error_notification %>

  <div class="col-xs-1 new move_number showRightBorder"><%= f.text_field :move_number, :class => "form-control input-sm", :placeholder => "#" %></div>
  <div class="col-xs-1 new piece_white"><%= f.select :piece_white, [['...','...'],['♟','♟'],['♞','♞'],['♝','♝'],['♜','♜'],['♛','♛'],['♚','♚']],{}, {:class => 'form-control input-sm'}%></div>
  <div class="col-xs-1 new start_white"><%= f.text_field :starting_coordinate_white, :class => 'form-control input-sm', :placeholder => "strt"  %></div>
  <div class="col-xs-1 new end_white showRightBorder"><%= f.text_field :ending_coordinate_white, :class => 'form-control input-sm', :placeholder => "end"  %></div>
  <div class="col-xs-1 new piece_black"><%= f.select :piece_black, [['...','...'],['♟','♟'],['♞','♞'],['♝','♝'],['♜','♜'],['♛','♛'],['♚','♚']],{}, {:class => 'form-control input-sm'}%></div>
  <div class="col-xs-1 new start_black"><%= f.text_field :starting_coordinate_black, :class => 'form-control input-sm', :placeholder => "strt"  %></div>
  <div class="col-xs-1 new end_black showRightBorder"><%= f.text_field :ending_coordinate_black, :class => 'form-control input-sm', :placeholder => "end"  %></div>
  <div class="col-xs-4 new explanation  showRightBorder"><%= f.text_area :explanation, :class => 'form-control text_area', :rows =>'1' %></div>  
  <div class="col-xs-1 new computer  showRightBorder"><%= f.radio_button :computer, true %> White
  <%= f.radio_button :computer, false %> Black </div>
  

  <div class="col-xs-1 new exercise_title  showRightBorder"><%= f.collection_select :exercise_id, Exercise.all, :id, :title, {:include_blank => true}, {:class => 'form-control input-sm'} %></div>
  <div class="col-xs-1 new updated"></div>
  <div class="col-xs-1 new"><%= f.submit "Add", :class => 'new btn btn-primary', :id => 'commit-Move' %></div>

<% end %>

app/views/moves/_move.html.erb
<div class="row move" id="move_<%= move.id %>" data-movenumber="<%= move.move_number %>" data-white="<%= move.piece_white %>:<%= move.starting_coordinate_white %>-<%= move.ending_coordinate_white %>" data-black="<%= move.piece_black %>:<%= move.starting_coordinate_black %>-<%= move.ending_coordinate_black %>" data-moveid="<%= move.id %>">
<!--     <div class="col-xs-1 move_id"></div> -->
    <div class="col-xs-1 move_number"><%= move.move_number %></div>
    <div class="col-xs-1 piece_white"><%= move.piece_white %></div>
    <div class="col-xs-1 start_white"><%= move.starting_coordinate_white %></div>
    <div class="col-xs-1 end_white"><%= move.ending_coordinate_white %></div>
    <div class="col-xs-1 piece_black"><%= move.piece_black %></div>
    <div class="col-xs-1 start_black"><%= move.starting_coordinate_black %></div>
    <div class="col-xs-1 end_black"><%= move.ending_coordinate_black %></div>
    <div class="col-xs-4 explanation"><%= move.explanation %></div>
    <div class="col-xs-1 computer"><%= move.computer ? "White" : "Black" %></div>
    <div class="col-xs-1 exercise_title"><%= move.exercise.nil? ? "" : move.exercise.title %></div>     
    <div class="col-xs-1 updated"><%= move.updated_at.strftime("%m/%d/%Y") %></div>
    <div class="col-xs-1 actions-button">
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
             <span class="glyphicon glyphicon-pencil"></span> <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Go To "+ move.id.to_s, move_path(move) %></li>
            <li><%= link_to('Edit',edit_move_url(move.id), :remote => true) %></li>
            <li><%= link_to('Delete', move_url(move.id), remote: true, method: :delete) %></li>
          </ul>
        </div>
    </div>    
</div>

app/views/moves/_moveList.html.erb
<!-- Headings -->
<div class="row">
  <div class="col-xs-1 moveHeader showRightBorder">Move#</div>
  <div class="col-xs-3 moveHeader showRightBorder">White</div>
  <div class="col-xs-3 moveHeader showRightBorder">Black</div>
  <div class="col-xs-4 moveHeader showRightBorder explanation">Explanation</div>
  <div class="col-xs-1 computer moveHeader showRightBorder">Computer</div>
  <div class="col-xs-1 exercise_title moveHeader showRightBorder">Exercise</div>
  <div class="col-xs-1 updated moveHeader showRightBorder">Updated</div>
  <div class="col-xs-1 moveHeader">Action</div>
</div>

<!-- Form for adding more MOVES -->
<div class="row" id="new_move_tr">
  <%= render('moves/formjs') %>
</div>

<!-- Rows of MOVES -->
<% show_moves.reverse.each do |move| %>
  <%= render('moves/move', :move => move) %>
<% end %>

<% if page_type === "Edit" %>
  <div class="row move" data-movenumber="0">
    <div class="col-xs-1 opening">0</div>
    <div class="col-xs-11 opening">Opening Setup</div>
  </div>
<% end %>

app/views/moves/edit.html.erb
<%- model_class = Move -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/moves/edit.js.erb
$("#<%= dom_id @move %>").replaceWith("<div class='row' id='editing_move_tr'><%= j(render('formjs')) %>");

app/views/moves/index.html.erb
<div class="row">
<%- model_class = Move -%>
	<div class="col-md-6">
		<div class="page-header">
			<h1><%= link_to "Moves", moves_path(format: "csv") %></h1>
		</div>  
	</div>  

  	<div class="col-md-6">

    	<!-- For uploading Moves -->
	    <%= link_to "CSV of All Moves", moves_path(format: "csv") %><br>
	    <%= form_tag import_moves_path, multipart: true do %>
	    <div class="fileinput fileinput-new" data-provides="fileinput">
	      <div class="input-group">
	        <div class="form-control uneditable-input" data-trigger="fileinput">
	          <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span>
	        </div>
	        <span class="input-group-addon btn btn-default btn-file">
	          <span class="fileinput-new">Select file</span>
	          <span class="fileinput-exists">Change</span>
	          <%= file_field_tag :file %>
	        </span>
	        <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
	        <%= submit_tag "Upload", :class => "upload input-group-addon btn btn-default fileinput-exists" %>
	      </div>
	    </div>
	    <% end %>
	</div>
</div>



<%= render('moveList', :model_class => Move, :show_moves => @moves, :page_type => "index") %>

app/views/moves/new.html.erb
<%- model_class = Move -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/moves/show.html.erb
<%- model_class = Move -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:move_number) %>:</strong></dt>
  <dd><%= @move.move_number %></dd>  
  <dt><strong><%= model_class.human_attribute_name(:piece_white) %>:</strong></dt>
  <dd><%= @move.piece_white %></dd>
  <dt><strong><%= model_class.human_attribute_name(:starting_coordinate_white) %>:</strong></dt>
  <dd><%= @move.starting_coordinate_white %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ending_coordinate_white) %>:</strong></dt>
  <dd><%= @move.ending_coordinate_white %></dd>
  <dt><strong><%= model_class.human_attribute_name(:piece_black) %>:</strong></dt>
  <dd><%= @move.piece_black %></dd>
  <dt><strong><%= model_class.human_attribute_name(:starting_coordinate_black) %>:</strong></dt>
  <dd><%= @move.starting_coordinate_black %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ending_coordinate_black) %>:</strong></dt>
  <dd><%= @move.ending_coordinate_black %></dd>
  <dt><strong><%= model_class.human_attribute_name(:explanation) %>:</strong></dt>
  <dd><%= @move.explanation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:exercise_id) %>:</strong></dt>
  <dd><%= @move.exercise.nil? ? "" : @move.exercise.title %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              moves_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_move_path(@move), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              move_path(@move),
              :method => 'delete',
              :class => 'btn btn-danger' %>
</div>

app/views/moves/update.js.erb
$("#editing_move_tr").replaceWith("<%= escape_javascript(render('move', :move => @move)) %>")