config/routes.rb
NoMercyChess::Application.routes.draw do
  resources :completions

  resources :lessons do 
    collection do
      #used for lesson building
      get 'builder'
      get :csv
      post :import
    end
    member do
      #used for a "test" at the end of a lesson
      get 'quizzes'
      get 'clone'
      get 'csv_lesson'
      get 'csv_lesson_moves'
      get 'csv_lesson_exercises'
    end
  end

  resources :exercises do
    collection do
      get :csv
      post :import
    end
    member do
      get 'practice'
      get 'clone'
      get 'quiz'
      get 'csv'
      # get 'builder'
    end
  end
  resources :moves do
    collection do
      get :csv
      post :import
    end
  end

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users

  get "home/pricing" 
  get "home/usedids"
  get "home/philosophy" 

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  attr_accessible :description, :title, :label

  #Lessons contain multiple exercises and tests - the user does a lesson which means working through several exercises
  has_many :exercises

  has_many :completions, :through => :exercises

  def next_exercise(exercise)
  	exercises.find_by_sort_for_lesson(exercise.sort_for_lesson + 1)
  end

  def sorted_exercises
  	exercises.sort_by { |exercise| exercise.sort_for_lesson }
  end

  def find_percent_complete(completionType, user_id)
    count = 0
    exercises.each do |exercise|
      count = count + exercise.completions.where(:last_completed => completionType, :user_id => user_id).count
    end
    count = count.to_f / (exercises.count*3)*100
    return count
  end

  def find_percent_complete_all(user_id)
    return find_percent_complete("exercise", user_id) + find_percent_complete("practice", user_id) + find_percent_complete("quiz", user_id)
  end

  # this is duplication of what is in the "moves"
  def self.to_csv(all_items)
    CSV.generate do |csv|
      csv << column_names
      all_items.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # Move.create! row.to_hash
      if find_by_id(row["id"])
        item = find_by_id(row["id"])
        item.attributes = row.to_hash.slice(*accessible_attributes)
        item.save!
      else
        item = Lesson.new
        item.attributes = row.to_hash.slice(*accessible_attributes)
        #this is code where I am going to try something)
        item.id = row.to_hash.slice("id")["id"].to_i
      
        item.save!
      end
    end
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessons }
      format.csv { 
        send_data(
          Lesson.to_csv(@lessons),
          :type => 'text/csv',
          :filename => 'lessons.csv',
          :disposition => 'attachment'
        ) 
      }
    end
  end

  # GET /lessons
  # GET /lessons.json
  def builder
    @lessons = Lesson.order("id DESC").all
    @exercises = Exercise.order("sort_for_lesson DESC").all
    respond_to do |format|
      format.html # builder.html.erb
      format.json { render json: @lessons }
    end
  end
  
  # used to download csv of exercises for a specific lesson
  # GET /lessons/1.csv
  def csv_lesson

    lesson = [Lesson.find(params[:id])]
    send_data(
      Lesson.to_csv(lesson),
      :type => 'text/csv',
      :filename => lesson[0].title + '-lesson.csv',
      :disposition => 'attachment'
    )
  end

  def csv_lesson_exercises
    lesson = Lesson.find(params[:id])
    @exercises = lesson.exercises
    send_data(
      Exercise.to_csv(@exercises),
      :type => 'text/csv',
      :filename => lesson.title + '-exercises.csv',
      :disposition => 'attachment'
    )
  end

  def csv_lesson_moves
    lesson = Lesson.find(params[:id])
    @exercises = lesson.exercises
    @all_moves = []
    @exercises.each do |exercise|
      exercise.moves.each do |move|
        @all_moves << move
      end
    end
    send_data(
      Move.to_csv(@all_moves),
      :type => 'text/csv',
      :filename => lesson.title + '-moves.csv',
      :disposition => 'attachment'
    )
  end
  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def quizzes

    if user_signed_in?
      # get all exercises in the lesson
      exercises_to_quiz = Lesson.find(params[:id]).exercise_ids
      
      #get lesson's exercises that have been quizzed
      completed_quizzes = Lesson.find(params[:id]).completions.where(:user_id => current_user.id, :last_completed => 'quiz')

      #remove exercises that have completed quizzes
      completed_quizzes.each do |quizzed|
        exercises_to_quiz.delete(quizzed.exercise_id)
      end

      if exercises_to_quiz.empty?
        redirect_to lesson_path(params[:id])
      else        
        #redirect to the next quiz
        redirect_to quiz_exercise_path(exercises_to_quiz.first)
      end
    end
  
  end

  # GET /lessons/new
  # GET /lessons/new.json
  def new
    @lesson = Lesson.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(params[:lesson])

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to builder_lessons_path, notice: 'Lesson was successfully created.' }
        format.json { render json: @lesson, status: :created, location: @lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to builder_lessons_path, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to builder_lessons_path }
      format.json { head :no_content }
    end
  end

  def clone
    @lesson = Lesson.find(params[:id]).dup

    if @lesson.save
      flash[:notice] = 'Item was successfully cloned.'
    else
      flash[:notice] = 'ERROR: Item can\'t be cloned.'
    end

    redirect_to(builder_lessons_path)
  end

  def import
    Lesson.import(params[:file])
    redirect_to builder_lessons_path, notice: "Lessons imported."
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_builderPartial.html.erb
<div id="<%= exercise.id %>" class="well well-sm">
	<%= link_to exercise.title, exercise_path(exercise) %>

	<%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, exercise_path(exercise), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-xs btn-danger pull-right' %>
	<%= link_to 'Dup', clone_exercise_path(exercise.id), :class => 'btn btn-default btn-xs pull-right' %>
	<%= link_to '<span class="glyphicon glyphicon-download-alt"></span>'.html_safe, csv_exercise_path(exercise), :class => 'btn btn-default btn-xs pull-right' %>
	<%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_exercise_path(exercise), :class => 'btn btn-default btn-xs pull-right' %>

</div>

app/views/lessons/_form.html.erb
<%= form_for @lesson, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :label, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :label, :class => 'text_field' %>
    </div>
  </div>
  <br>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                builder_lessons_path, :class => 'btn' %>
  </div>
<% end %>

app/views/lessons/builder.html.erb
<div class="row">

  <div class="col-md-6">
    <div class="page-header">
     <h1>Claimed  <%= link_to 'New Lesson', new_lesson_path, :class => 'btn btn-primary pull-right' %><%= link_to 'New Exercise', new_exercise_path, :class => 'btn btn-primary pull-right' %></h1> 
    </div>
   <% @lessons.each do |lesson| %>
    <h4>
      <%= link_to lesson.title, lesson_path(lesson) %>
      <div class="btn-group pull-right">
        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
          Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to '<span class="glyphicon glyphicon-download-alt"> Lesson</span>'.html_safe, csv_lesson_lesson_path(lesson), :class => "lesson" + lesson.id.to_s %></li>
          <li><%= link_to '<span class="glyphicon glyphicon-download-alt"> Exercises</span>'.html_safe, csv_lesson_exercises_lesson_path(lesson), :class => "lesson" + lesson.id.to_s  %></li>
          <li><%= link_to '<span class="glyphicon glyphicon-download-alt"> Moves</span>'.html_safe, csv_lesson_moves_lesson_path(lesson), :class => "lesson" + lesson.id.to_s, :id => "lesson12"  %></li>
          <li><%= link_to '<span class="glyphicon glyphicon-edit"> Edit</span>'.html_safe, edit_lesson_path(lesson) %></li>
          <li><%= link_to '<span class="glyphicon glyphicon-random"> Duplicate</span>'.html_safe, {:action => "clone", :id => lesson.id} %></li>
          <li><%= link_to '<span class="glyphicon glyphicon-trash"> Delete</span>'.html_safe, lesson_path(lesson), :method => :delete, :data => { :confirm => 'Are you sure?' } %></li>
        </ul>
      </div>

    </h4>
    <div id="<%= lesson.id %>" class="connectedSortable canSort well">

     <% lesson.exercises.sort_by{|exercise| exercise.sort_for_lesson}.each do |exercise| %>
        <%= render('builderPartial', :exercise => exercise) %>
     <%end%>
    </div>
   <% end %>
  </div>

  <div class="col-md-6">

    <div class="page-header">
     <h1>Bulk Import/Export</h1>
    </div>

    <!-- For uploading Moves -->
    <%= link_to "CSV of All Moves", moves_path(format: "csv") %><br>
    <%= form_tag import_moves_path, multipart: true do %>
    <div class="fileinput fileinput-new input-group" data-provides="fileinput">
      <div class="input-group">
        <div class="form-control uneditable-input" data-trigger="fileinput">
          <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span>
        </div>
        <span class="input-group-addon btn btn-default btn-file">
          <span class="fileinput-new ">Select file</span>
          <span class="fileinput-exists">Change</span>
          <%= file_field_tag :file %>
        </span>
        <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
        <%= submit_tag "Upload", :class => "upload input-group-addon btn btn-default fileinput-exists" %>
      </div>
    </div>
    <% end %>

    <!-- For uploading Exercises -->
    <%= link_to "CSV of All Exercises", exercises_path(format: "csv") %><br>
    <%= form_tag import_exercises_path, multipart: true do %>
    <div class="fileinput fileinput-new" data-provides="fileinput">
      <div class="input-group">
        <div class="form-control uneditable-input" data-trigger="fileinput">
          <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span>
        </div>
        <span class="input-group-addon btn btn-default btn-file">
          <span class="fileinput-new">Select file</span>
          <span class="fileinput-exists">Change</span>
          <%= file_field_tag :file %>
        </span>
        <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
        <%= submit_tag "Upload", :class => "upload input-group-addon btn btn-default fileinput-exists" %>
      </div>
    </div>
    <% end %>

    <!-- For uploading Lessons -->
    <%= link_to "CSV of All Lessons", lessons_path(format: "csv") %><br>
    <%= form_tag import_lessons_path, multipart: true do %>
    <div class="fileinput fileinput-new" data-provides="fileinput">
      <div class="input-group">
        <div class="form-control uneditable-input" data-trigger="fileinput">
          <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span>
        </div>
        <span class="input-group-addon btn btn-default btn-file">
          <span class="fileinput-new">Select file</span>
          <span class="fileinput-exists">Change</span>
          <%= file_field_tag :file %>
        </span>
        <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
        <%= submit_tag "Upload", :class => "upload input-group-addon btn btn-default fileinput-exists" %>
      </div>
    </div>
    <% end %>


    <div class="page-header">
     <h1>Unclaimed</h1>
    </div>
    <div class="connectedSortable canSort well">
     <% @exercises.each do |exercise| %>
      <% if exercise.lesson_id.nil?  %>
        <%= render('builderPartial', :exercise => exercise) %>
      <%end%>
     <% end %>
    </div>
  </div>
</div>

app/views/lessons/edit.html.erb
<%- model_class = Lesson -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lessons/index.html.erb
<% number_of_rows = (@lessons.count.to_f/4).ceil %>
<% start_lesson_for_row = 0 %>
<% end_lesson_for_row = 3 %>

<div class="row">
  <div class="col-md-4">
    <%- model_class = Lesson -%>
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
    </div>
  </div>
  <div class="col-md-8">
  </div>
</div>

<% number_of_rows.times do |lesson| %>
  <div class="row">
    <% @lessons[start_lesson_for_row..end_lesson_for_row].each do |lesson| %> 
      <div class="col-md-3">
        <div class="thumbnail">
          <!-- <img alt="300x200" src="http://placehold.it/400x200"> -->
          <p class="lesson-pic text-center">♟</p>
          <div class="caption">
            <h3 class="text-center"><%= lesson.title%></h3>
            <p class="text-justify"><%= lesson.description.first(80) %>...</p>

            <% if !current_user.nil? %>
              <div class="progress">
                <div class="bar bar-success" style="width: <%= number_to_percentage(lesson.find_percent_complete("exercise", current_user.id)) %>;"></div>
                <div class="bar bar-warning" style="width: <%= number_to_percentage(lesson.find_percent_complete("practice", current_user.id)) %>;"></div>
                <div class="bar bar-danger" style="width: <%= number_to_percentage(lesson.find_percent_complete("quiz", current_user.id)) %>;"></div>
              </div>
                
              <% if number_to_percentage(lesson.find_percent_complete("exercise", current_user.id) + lesson.find_percent_complete("practice", current_user.id) + lesson.find_percent_complete("quiz", current_user.id)) === number_to_percentage(100.00) %>
               <p><%= link_to 'Completed!', lesson_path(lesson.id), :class => 'btn btn-lg btn-primary' %></p> 
              <% elsif number_to_percentage(lesson.find_percent_complete("exercise", current_user.id) + lesson.find_percent_complete("practice", current_user.id) + lesson.find_percent_complete("quiz", current_user.id)) === number_to_percentage(0)%>
               <p><%= link_to 'Do It!', lesson_path(lesson.id), :class => 'btn btn-lg btn-primary' %></p> 
              <% else %>
               <p><%= link_to 'Continue...', lesson_path(lesson.id), :class => 'btn btn-lg btn-primary' %></p> 
              <% end %>

            <% else %>
              <p><%= link_to 'Do It!', lesson_path(lesson.id), :class => 'btn btn-lg btn-primary' %></p> 
            <% end %> 
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% start_lesson_for_row = start_lesson_for_row +3 %>
  <% end_lesson_for_row = end_lesson_for_row +3 %>
<% end %>

app/views/lessons/new.html.erb
<%- model_class = Lesson -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lessons/quizzes.html.erb
  here?
  <% if !@exercises_to_quiz.nil? %>
	<%= @exercises_to_quiz.count %>
	<ul>
     <% @exercises_to_quiz.each do |quiz| %> 
      <li>

      	<%= quiz %>
      </li>
     <% end %>
    </ul>
  <% end %>

app/views/lessons/show.html.erb
<%- model_class = Lesson -%>
<div class="page-header">
  <h1>
    <%=t '.title', :default => @lesson.title %> <%= link_to "Let's Go!", exercise_path(@lesson.sorted_exercises.first), :class => 'btn btn-primary btn-lg' %>
  </h1>
</div>

<dl class="dl-horizontal">
<!--   <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @lesson.title %></dd> -->
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @lesson.description %></dd>
</dl>
<div class="row">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Exercise Name</th>
          <th>Exercise</th>
          <th>Practice</th>
        </tr>
      </thead>
      <tbody>
        <% @lesson.sorted_exercises.each do |exercise| %> 
        <tr>
          <td><%= link_to exercise.title, exercise_path(exercise) %></td>
          
          <% if !current_user.nil? %>
            <% exerciseDone = exercise.isDoneForUser("exercise", current_user.id) %>
            <% practiceDone = exercise.isDoneForUser("practice", current_user.id) %>
          <% end %> 
          
          <td><%= link_to exerciseDone.nil? ? "Do it Now!" : "Completed " + time_ago_in_words(exerciseDone) + " ago", exercise_path(exercise) %></td>
          <td><%= link_to practiceDone.nil? ? "Do it Now!" : "Completed " + time_ago_in_words(practiceDone) + " ago", practice_exercise_path(exercise) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    
  <% if !current_user.nil? %>
    <div class="progress">
      <div class="bar bar-success" style="width: <%= number_to_percentage(@lesson.find_percent_complete("exercise", current_user.id)) %>;"></div>
      <div class="bar bar-warning" style="width: <%= number_to_percentage(@lesson.find_percent_complete("practice", current_user.id)) %>;"></div>
      <div class="bar bar-danger" style="width: <%= number_to_percentage(@lesson.find_percent_complete("quiz", current_user.id)) %>;"></div>
    </div>
  <% end %> 
  
  </div>
</div>

<% if !current_user.nil? %>
  <% if (@lesson.find_percent_complete("exercise", current_user.id) === 1.to_f / 3 * 100) && (@lesson.find_percent_complete("practice", current_user.id) === 1.to_f / 3 * 100) && (@lesson.find_percent_complete("quiz", current_user.id) != 1.to_f / 3 * 100) %>
    <%= link_to "Quiz Me!", quizzes_lesson_path(@lesson), :class => 'btn btn-danger btn-lg' %>
  <% end %>
<% end %>



  