config/routes.rb
NoMercyChess::Application.routes.draw do
  resources :completions

  resources :lessons do 
    collection do
      #used for lesson building
      get 'builder'
      get :csv
      post :import
    end
    member do
      #used for a "test" at the end of a lesson
      get 'quizzes'
      get 'clone'
      get 'csv_lesson'
      get 'csv_lesson_moves'
      get 'csv_lesson_exercises'
    end
  end

  resources :exercises do
    collection do
      get :csv
      post :import
    end
    member do
      get 'practice'
      get 'clone'
      get 'quiz'
      get 'csv'
      # get 'builder'
    end
  end
  resources :moves do
    collection do
      get :csv
      post :import
    end
  end

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users

  get "home/pricing" 
  get "home/usedids"
  get "home/philosophy" 

end

app/models/completion.rb
class Completion < ActiveRecord::Base
  attr_accessible :exercise_id, :last_completed, :user_id

    belongs_to :user
    belongs_to :exercise
    belongs_to :lesson

end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  # GET /completions
  # GET /completions.json
  def index
    @completions = Completion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @completions }
    end
  end

  # GET /completions/1
  # GET /completions/1.json
  def show
    @completion = Completion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @completion }
    end
  end

  # GET /completions/new
  # GET /completions/new.json
  def new
    @completion = Completion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @completion }
    end
  end

  # GET /completions/1/edit
  def edit
    @completion = Completion.find(params[:id])
  end

  # POST /completions
  # POST /completions.json
  def create
    @completion = Completion.new(params[:completion])

    respond_to do |format|
      if @completion.save
        format.html { redirect_to @completion, notice: 'Completion was successfully created.' }
        format.json { render json: @completion, status: :created, location: @completion }
      else
        format.html { render action: "new" }
        format.json { render json: @completion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /completions/1
  # PUT /completions/1.json
  def update
    @completion = Completion.find(params[:id])

    respond_to do |format|
      if @completion.update_attributes(params[:completion])
        format.html { redirect_to @completion, notice: 'Completion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @completion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /completions/1
  # DELETE /completions/1.json
  def destroy
    @completion = Completion.find(params[:id])
    @completion.destroy

    respond_to do |format|
      format.html { redirect_to completions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/completions_helper.rb
module CompletionsHelper
end

app/views/completions/_form.html.erb
<%= simple_form_for(@completion) do |f| %>
  <%= f.error_notification %>
  <div class="control-group">
    <%= f.label :exercise_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :exercise_id, Exercise.all, :id, :title, :include_blank => true %>
    </div>
  </div>
  <div class="form-inputs">
    <%= f.input :user_id %>
  </div>
  <div class="control-group">
    <%= f.label :last_completed, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :last_completed, [['exercise','exercise'],['practice','practice'],['quiz','quiz']]%>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/completions/edit.html.erb
<h1>Editing completion</h1>

<%= render 'form' %>

<%= link_to 'Show', @completion %> |
<%= link_to 'Back', completions_path %>

app/views/completions/index.html.erb
<h1>Listing completions</h1>

<table class= 'table table-striped table-bordered table-condensed table-hover'>
  <tr>
    <th>User</th>
    <th>Exercise</th>
    <th>Last completed</th>
    <th></th>
  </tr>

<% @completions.each do |completion| %>
  <tr>
  <% if completion.user.nil? %>
    <td> User Does Not Exist </td>
  <% else %>
    <td><%= completion.user.name %></td>
  <% end %>
    <td><%= completion.exercise.title %></td>
    <td><%= completion.last_completed %></td>
    <td>
      <%= link_to 'Show', completion, :class => 'btn btn-mini btn-primary' %>
      <%= link_to 'Edit', edit_completion_path(completion), :class => 'btn btn-mini' %>
      <%= link_to 'Destroy', completion, method: :delete, :class => 'btn btn-mini btn-danger' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Completion', new_completion_path %>

app/views/completions/new.html.erb
<h1>New completion</h1>

<%= render 'form' %>

<%= link_to 'Back', completions_path %>

app/views/completions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @completion.user_id %>
</p>

<p>
  <b>Exercise:</b>
  <%= @completion.exercise_id %>
</p>

<p>
  <b>Last completed:</b>
  <%= @completion.last_completed %>
</p>


<%= link_to 'Edit', edit_completion_path(@completion) %> |
<%= link_to 'Back', completions_path %>