config/routes.rb
NoMercyChess::Application.routes.draw do
  resources :completions

  resources :lessons do 
    collection do
      #used for lesson building
      get 'builder'
      get :csv
      post :import
    end
    member do
      #used for a "test" at the end of a lesson
      get 'quizzes'
      get 'clone'
      get 'csv_lesson'
      get 'csv_lesson_moves'
      get 'csv_lesson_exercises'
    end
  end

  resources :exercises do
    collection do
      get :csv
      post :import
    end
    member do
      get 'practice'
      get 'clone'
      get 'quiz'
      get 'csv'
      # get 'builder'
    end
  end
  resources :moves do
    collection do
      get :csv
      post :import
    end
  end

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users

  get "home/pricing" 
  get "home/usedids"
  get "home/philosophy" 

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
  <li>
    <%= link_to 'Build A Lesson', builder_lessons_path %>
  </li>   
  <li id="fat-menu" class="dropdown">
    <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
      <li><%= link_to 'My Account', edit_user_registration_path %></li>
      <% if current_user.has_role? :admin %>
        <li><%= link_to 'Admin', users_path %></li>
      <% end %>
      <li class="divider"></li>
      <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
    </ul>
  </li>
  <% else %>
    <li id="nav-log" data-navid= "navigation-0">
    <%= link_to 'Sign In', new_user_session_path %>  
    </li>
    <li>
    <%= link_to 'Sign Up', new_user_registration_path %> 
    </li>
  <% end %>
</ul>
<ul class='nav navbar-nav'>
<!--    <li>
    <%= link_to 'Pricing', home_pricing_path %>
  </li>  -->
<!--   <li>
    <%= link_to 'Exercises', exercises_path %>
  </li>  -->
  <li>
    <%= link_to 'Lessons', lessons_path %>
  </li>
  <li>
    <%= link_to 'Build A Lesson', builder_lessons_path %>
  </li>   
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nomercychess" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Nomercychess" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "NoMercyChess", root_path, :class => 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse">
          <%= render 'layouts/navigation' %>
        </div><!--/.nav-collapse -->
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
          <%= render 'layouts/messages' %>
          <%= yield %>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>